version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
            target: app
        container_name: playground-app
        ports:
            - "8080:80"
        networks:
            - playground

networks:
    playground:
